//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildirim
    {
        public int bildirim_id { get; set; }
        public Nullable<int> tur_id { get; set; }
        public string personel_tc { get; set; }
        public string session_personel_tc { get; set; }
        public string mesaj { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> goruldu_mu { get; set; }
    
        public virtual BildirimTur BildirimTur { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Personel Personel1 { get; set; }
    }
}
