//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosya
    {
        public int dosya_id { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public string yukleyen_personel_tc { get; set; }
        public Nullable<int> iliskili_firma_id { get; set; }
        public string baslik { get; set; }
        public string yol { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string uzanti { get; set; }
        public Nullable<bool> silindi_mi { get; set; }
    
        public virtual DosyaKategori DosyaKategori { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
