//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaDurum
    {
        public FirmaDurum()
        {
            this.Firma = new HashSet<Firma>();
        }
    
        public int durum_id { get; set; }
        public string ad { get; set; }
        public string arkaplan_rengi { get; set; }
    
        public virtual ICollection<Firma> Firma { get; set; }
    }
}
