//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public Firma()
        {
            this.FirmaYetkili = new HashSet<FirmaYetkili>();
            this.Is = new HashSet<Is>();
            this.Ziyaret = new HashSet<Ziyaret>();
        }
    
        public int firma_id { get; set; }
        public string cari_kod { get; set; }
        public Nullable<int> durum_id { get; set; }
        public string sgk_no { get; set; }
        public string vergi_daire { get; set; }
        public string vergi_no { get; set; }
        public string unvan { get; set; }
        public string kisa_ad { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public string adres { get; set; }
        public Nullable<double> enlem { get; set; }
        public Nullable<double> boylam { get; set; }
        public Nullable<bool> silindi_mi { get; set; }
    
        public virtual ICollection<FirmaYetkili> FirmaYetkili { get; set; }
        public virtual FirmaDurum FirmaDurum { get; set; }
        public virtual ICollection<Is> Is { get; set; }
        public virtual ICollection<Ziyaret> Ziyaret { get; set; }
    }
}
