//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Is
    {
        public Is()
        {
            this.Sikayet = new HashSet<Sikayet>();
            this.IsPersonelOrtak = new HashSet<IsPersonelOrtak>();
        }
    
        public int is_id { get; set; }
        public Nullable<int> tur_id { get; set; }
        public Nullable<int> firma_id { get; set; }
        public Nullable<int> durum_id { get; set; }
        public string baslik { get; set; }
        public Nullable<System.DateTime> kayit_tarih { get; set; }
        public Nullable<int> sure { get; set; }
        public Nullable<double> ucret { get; set; }
        public Nullable<double> alinan_ucret { get; set; }
        public Nullable<double> aylik_ucret { get; set; }
        public Nullable<double> yillik_ucret { get; set; }
        public string sozlesme { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> silindi_mi { get; set; }
        public string sorumlu_personel { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual IsDurum IsDurum { get; set; }
        public virtual IsTur IsTur { get; set; }
        public virtual ICollection<Sikayet> Sikayet { get; set; }
        public virtual ICollection<IsPersonelOrtak> IsPersonelOrtak { get; set; }
    }
}
