//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsPersonelOrtak
    {
        public int kayit_id { get; set; }
        public Nullable<int> is_id { get; set; }
        public string personel_tc { get; set; }
        public Nullable<System.DateTime> gorev_baslama_tarih { get; set; }
        public Nullable<System.DateTime> gorev_sonlanma_tarih { get; set; }
        public string aciklama { get; set; }
    
        public virtual Is Is { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
