//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int log_id { get; set; }
        public Nullable<int> tur_id { get; set; }
        public string personel_tc { get; set; }
        public string ip_adres { get; set; }
        public string bilgisayar_ad { get; set; }
        public string aktif_sayfa { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string mesaj { get; set; }
    
        public virtual LogTur LogTur { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
