//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailAyar
    {
        public int id { get; set; }
        public string mail { get; set; }
        public string sifre { get; set; }
        public string host { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<bool> ssl { get; set; }
    }
}
