//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesaiKayit
    {
        public int kayit_id { get; set; }
        public string personel_tc { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.TimeSpan> giris_saat { get; set; }
        public Nullable<System.TimeSpan> cikis_saat { get; set; }
        public Nullable<double> giris_enlem { get; set; }
        public Nullable<double> giris_boylam { get; set; }
        public Nullable<double> cikis_enlem { get; set; }
        public Nullable<double> cikis_boylam { get; set; }
        public Nullable<double> giris_fark { get; set; }
        public Nullable<double> cikis_fark { get; set; }
        public Nullable<double> ek_mesai { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
