//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbIsTakipEntities : DbContext
    {
        public dbIsTakipEntities()
            : base("name=dbIsTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DosyaKategori> DosyaKategori { get; set; }
        public virtual DbSet<Firma> Firma { get; set; }
        public virtual DbSet<FirmaYetkili> FirmaYetkili { get; set; }
        public virtual DbSet<Gelir> Gelir { get; set; }
        public virtual DbSet<GelirKategori> GelirKategori { get; set; }
        public virtual DbSet<Gider> Gider { get; set; }
        public virtual DbSet<GiderKategori> GiderKategori { get; set; }
        public virtual DbSet<IsDurum> IsDurum { get; set; }
        public virtual DbSet<IsTur> IsTur { get; set; }
        public virtual DbSet<PersonelDepartman> PersonelDepartman { get; set; }
        public virtual DbSet<PersonelMaas> PersonelMaas { get; set; }
        public virtual DbSet<PersonelTip> PersonelTip { get; set; }
        public virtual DbSet<Sikayet> Sikayet { get; set; }
        public virtual DbSet<ZiyaretTur> ZiyaretTur { get; set; }
        public virtual DbSet<MailAyar> MailAyar { get; set; }
        public virtual DbSet<Hata> Hata { get; set; }
        public virtual DbSet<FirmaDurum> FirmaDurum { get; set; }
        public virtual DbSet<Is> Is { get; set; }
        public virtual DbSet<SirketProfilBilgileri> SirketProfilBilgileri { get; set; }
        public virtual DbSet<MesaiKayit> MesaiKayit { get; set; }
        public virtual DbSet<Bildirim> Bildirim { get; set; }
        public virtual DbSet<BildirimTur> BildirimTur { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolHak> RolHak { get; set; }
        public virtual DbSet<Hak> Hak { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<LogTur> LogTur { get; set; }
        public virtual DbSet<IsPersonelOrtak> IsPersonelOrtak { get; set; }
        public virtual DbSet<Ziyaret> Ziyaret { get; set; }
        public virtual DbSet<Dosya> Dosya { get; set; }
    }
}
