//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public Personel()
        {
            this.Bildirim = new HashSet<Bildirim>();
            this.Bildirim1 = new HashSet<Bildirim>();
            this.DosyaKategori = new HashSet<DosyaKategori>();
            this.MesaiKayit = new HashSet<MesaiKayit>();
            this.PersonelMaas = new HashSet<PersonelMaas>();
            this.Log = new HashSet<Log>();
            this.IsPersonelOrtak = new HashSet<IsPersonelOrtak>();
            this.Ziyaret = new HashSet<Ziyaret>();
            this.Dosya = new HashSet<Dosya>();
        }
    
        public string personel_tc { get; set; }
        public Nullable<int> departman_id { get; set; }
        public Nullable<int> tip_id { get; set; }
        public Nullable<int> kullanici_rol_id { get; set; }
        public string sicil_no { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<System.DateTime> dogum_tarih { get; set; }
        public string fotograf { get; set; }
        public string mail { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string unvan { get; set; }
        public Nullable<System.DateTime> ise_giris_tarih { get; set; }
        public Nullable<System.DateTime> isten_cikis_tarih { get; set; }
        public Nullable<double> guncel_maas { get; set; }
        public Nullable<double> ek_mesai_ucret { get; set; }
        public Nullable<System.TimeSpan> varsayilan_giris_saat { get; set; }
        public Nullable<System.TimeSpan> varsayilan_cikis_saat { get; set; }
        public string sifre { get; set; }
        public Nullable<bool> silindi_mi { get; set; }
    
        public virtual ICollection<Bildirim> Bildirim { get; set; }
        public virtual ICollection<Bildirim> Bildirim1 { get; set; }
        public virtual ICollection<DosyaKategori> DosyaKategori { get; set; }
        public virtual ICollection<MesaiKayit> MesaiKayit { get; set; }
        public virtual ICollection<PersonelMaas> PersonelMaas { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual PersonelDepartman PersonelDepartman { get; set; }
        public virtual PersonelTip PersonelTip { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<IsPersonelOrtak> IsPersonelOrtak { get; set; }
        public virtual ICollection<Ziyaret> Ziyaret { get; set; }
        public virtual ICollection<Dosya> Dosya { get; set; }
    }
}
