//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sikayet
    {
        public int kayit_id { get; set; }
        public Nullable<int> is_id { get; set; }
        public string fotograf { get; set; }
        public string baslik { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> cozuldu_mu { get; set; }
    
        public virtual Is Is { get; set; }
    }
}
