//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SirketProfilBilgileri
    {
        public int profilId { get; set; }
        public string unvan { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public string web { get; set; }
        public string adres { get; set; }
        public string faks { get; set; }
        public Nullable<double> enlem { get; set; }
        public Nullable<double> boylam { get; set; }
    }
}
