//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ziyaret
    {
        public int ziyaret_id { get; set; }
        public Nullable<int> tur_id { get; set; }
        public Nullable<int> firma_id { get; set; }
        public string personel_tc { get; set; }
        public string aciklama { get; set; }
        public Nullable<double> enlem { get; set; }
        public Nullable<double> boylam { get; set; }
        public string konum { get; set; }
        public Nullable<System.TimeSpan> saat { get; set; }
        public Nullable<System.DateTime> giris_tarih { get; set; }
        public Nullable<System.DateTime> cikis_tarih { get; set; }
        public Nullable<double> giris_fark { get; set; }
        public Nullable<double> cikis_fark { get; set; }
        public Nullable<bool> bildirim_goruldu_mu { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual ZiyaretTur ZiyaretTur { get; set; }
    }
}
